### ISSUE TITLE
NVME system for researcher while cache machines not yet available

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/moca-requests#1]
@mosayyebzadeh can you say more about what you need- could we put one or two of the cache servers live for the short term?

Edited: to remove personal email address.

**Comment by mosayyebzadeh** [comment]
@msdisme yes, it would be great. I need one or even better two servers with NVMe to run some initial micro-benchmarks to measure the performance gain we might get through our research idea.

**Comment by joachimweyl** [comment]
@hakasapl what are the next steps on this request? Can we get techsquared to do the hard drive install?

**Comment by hakasapl** [comment]
@joachimweyl The servers are in the rack and should be done cabled by today. 2x of them should be available next week. Also [this issue](https://github.com/CCI-MOC/ops-issues/issues/1051)

**Comment by msdisme** [comment]
@hakasapl any update on this?  Is Amin already using them?

**Comment by hakasapl** [comment]
Tracking progress on this [here](https://github.com/CCI-MOC/ops-issues/issues/1051). One of them is ready to go but we just need to verify which one techsquare plugged in so we can set it up

**Comment by hakasapl** [comment]
Closing this because [this](https://github.com/CCI-MOC/ops-issues/issues/1051) issue is closed. We will open a different issue for for the remaining nodes
